export const USER_EMAILS = [
    "mary_cervantes@salob.com",
    "margaret_black@salob.com",
    "ashley_cruz@salob.com",
    "juan_nixon@salob.com",
    "lisa_bishop@salob.com",
    "rodney_valentine@salob.com",
    "george_patterson@salob.com",
    "jennifer_garcia@salob.com",
    "gary_chavez@salob.com",
    "olivia_bradley@salob.com",
    "danielle_kimberly_bass@salob.com",
    "melissa_julia_lewis@salob.com",
    "zachary_jackson@salob.com",
    "timothy_roberts@salob.com",
    "heather_amy_martinez@salob.com",
];

export const USER_PASSWORD = "password"; // pragma: allowlist secret

export const FOOD_SEARCH_TERMS = [
    "Chicken Rice",
    "Hokkien Mee",
    "Char Kway Teow",
    "Laksa",
    "Nasi Lemak",
    "Roti Prata",
    "Satay",
    "Bak Kut Teh",
    "Mee Goreng",
    "Prawn Noodle",
    "Fish Soup",
    "Biryani",
    "Ramen",
    "Sushi",
    "Pasta",
    "Dim Sum",
    "Oyster Omelette",
    "Fried Chicken",
    "Curry Laksa",
    "Spaghetti Bolognese",
    "Tiramisu",
    "Gelato",
    "Baklava",
    "Fettuccine Alfredo",
    "Tandoori Chicken",
    // Dummy / negative-path terms
    "Unicorn Burger",
    "Galaxy Noodles",
    "Dragonfruit Rendang",
    "Moon Pie Supreme",
];

export const EATERY_SEARCH_TERMS = [
    "Maxwell Food Centre",
    "Amoy Street Food Centre",
    "Lau Pa Sat",
    "Old Airport Road Food Centre",
    "Changi Village Hawker Centre",
    "Holland Village Food Centre",
    "Chomp Chomp Food Centre",
    "Jurong Point Kopitiam",
    "Tiong Bahru Bakery",
    "Common Man Coffee Roasters",
    "PS.Cafe",
    "Din Tai Fung",
    "328 Katong Laksa",
    "Bedok 85",
    "Swee Choon Tim Sum",
    "McDonald's (Ang Mo Kio)",
    "KFC (Tampines Hub)",
    "Koi The (Plaza Singapura)",
    "Starbucks (Rochester Park)",
    "Food Republic (Wisma Atria)",
    // Address-based queries (EateryService searches name + address)
    "Orchard Road",
    "Tanjong Pagar Road",
    "East Coast Road",
    "Upper Thomson Road",
    "Bedok North Street",
    "Serangoon Central",
    "Bukit Timah Road",
    "Sunset Way",
    "Raffles Quay",
    "Rochester Drive",
    "Changi Village Road",
    "Hougang Street 21",
    // Dummy / negative-path terms
    "Atlantis Cafe",
    "Foo Bar Bistro",
    "Imaginary Food Court",
    "1234 Nowhere Road",
];
