spring:
  application:
    name: user-service
  config:
    import: "optional:file:.env.local[.properties]"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      port: ${GRPC_PORT}
      enable-reflection: true
server:
  port: ${APP_PORT}
jwt:
  secret: ${JWT_SECRET}
  exp-seconds: ${JWT_EXPIRATION_SECONDS}
debug: true
