package com.salob.food_service.api.eatery;

import com.salob.food_service.api._domain.Eatery;
import com.salob.food_service.api._domain.EateryType;
import com.salob.food_service.api._domain.Food;
import com.salob.food_service.api._domain.FoodEntry;
import com.salob.food_service.api._exceptions.EateryNotFoundException;
import com.salob.food_service.api.eatery.dto.EateryDetailedDTO;
import com.salob.food_service.api.eatery.dto.EateryMapDTO;
import com.salob.food_service.api.eatery.dto.EateryPreviewDTO;
import com.salob.food_service.common.ConfidenceAlgorithm;
import com.salob.food_service.storage.minio.MinioStorageService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/*
 * =============================================================================
 * WHAT THIS TEST TEACHES
 * =============================================================================
 *
 * 1. Mockito — a library that creates "fake" objects (mocks) that simulate
 *    real dependencies. You control what they return. You verify they're
 *    called correctly.
 *
 * 2. @ExtendWith(MockitoExtension.class) — tells JUnit 5 to use Mockito's
 *    extension. This makes @Mock and @InjectMocks work automatically.
 *
 * 3. @Mock — creates a mock (fake) of a class/interface. E.g.:
 *      @Mock EateryRepository eateryRepo;
 *    creates a fake EateryRepository that does nothing unless you tell it to.
 *
 * 4. when(mock.method()).thenReturn(value) — "when this method is called on
 *    the mock, return this value instead of executing the real method."
 *
 * 5. verify(mock).method(args) — "assert that this method WAS called with
 *    these arguments." This is how we prove the test exercised our code.
 *
 * 6. Constructor injection — EateryService uses @RequiredArgsConstructor
 *    (Lombok generates a constructor with all final fields). We can pass
 *    mocks directly: new EateryService(eateryRepo, confidenceAlgo, minio).
 *    This is the key insight: services are PLAIN Java objects with dependencies
 *    passed in — no Spring magic required in the test.
 * =============================================================================
 */

/*
 * @ExtendWith(MockitoExtension.class)
 *
 * This "registers" Mockito as a JUnit 5 extension. Without this, @Mock
 * fields would be null. The extension processes annotations like @Mock,
 * @InjectMocks, @Captor, etc. before each test.
 */
@ExtendWith(MockitoExtension.class)
class EateryServiceTest {

    /*
     * @Mock creates a fake object. Mockito tracks every call to it.
     * These mocks have NO behavior by default — they return null/0/false
     * for every method unless you stub them with when(...).thenReturn(...).
     */
    @Mock
    private EateryRepository eateryRepo;

    @Mock
    private ConfidenceAlgorithm confidenceAlgorithm;

    @Mock
    private MinioStorageService minioStorageService;

    /*
     * The object under test. We do NOT use @InjectMocks here because
     * we want to be EXPLICIT about how dependencies are wired.
     *
     * @InjectMocks would auto-inject our @Mock fields via constructor,
     * but it can silently inject wrong mocks if there are ambiguities.
     * Manual constructor call is safer and clearer.
     */
    private EateryService eateryService;

    /*
     * Shared test data — these are created fresh before each test.
     *
     * @BeforeEach methods run before each @Test. This guarantees
     * total isolation: no test can accidentally affect another.
     */
    private UUID eateryId;
    private Eatery testEatery;
    private EateryType testType;

    @BeforeEach
    void setUp() {
        /*
         * Manual construction of the service with mocked dependencies.
         * The constructor is generated by Lombok @RequiredArgsConstructor
         * since all fields are final. We pass in our @Mock objects.
         *
         * No Spring context needed — just a plain new + constructor call.
         */
        eateryService = new EateryService(eateryRepo, confidenceAlgorithm, minioStorageService);

        eateryId = UUID.randomUUID();

        testType = EateryType.builder()
                .label("Hawker Stall")
                .build();
        testType.setId(UUID.randomUUID());

        testEatery = Eatery.builder()
                .name("Test Hawker")
                .address("1 Test Street")
                .type(testType)
                .photoObjKey("test-photo-key")
                .build();
        testEatery.setId(eateryId);
        testEatery.setCreatedAt(Instant.now());
    }

    // =========================================================================
    // Test naming convention: methodName_scenario_expectedBehavior
    //
    // This makes test failures readable:
    //   "findById_whenExists_returnsEatery" — clear intent
    // =========================================================================

    // =========================================================================
    // SECTION 1: findById
    // =========================================================================

    @Test
    void findById_whenExists_returnsEatery() {
        /*
         * ARRANGE — set up the mock behavior.
         * "When eateryRepo.findById(eateryId) is called, return Optional.of(testEatery)"
         */
        when(eateryRepo.findById(eateryId)).thenReturn(Optional.of(testEatery));

        /*
         * ACT — call the method under test.
         */
        Eatery result = eateryService.findById(eateryId);

        /*
         * ASSERT — verify the result.
         */
        assertNotNull(result);
        assertEquals(eateryId, result.getId());
        assertEquals("Test Hawker", result.getName());

        /*
         * VERIFY — prove the mock was called as expected.
         * If findById was never called (e.g., the service used a different
         * method), this assertion fails.
         */
        verify(eateryRepo).findById(eateryId);
    }

    @Test
    void findById_whenNotExists_throwsEateryNotFoundException() {
        when(eateryRepo.findById(eateryId)).thenReturn(Optional.empty());

        /*
         * assertThrows verifies the EXACT exception type is thrown.
         * The lambda () -> eateryService.findById(eateryId) runs the code
         * that SHOULD throw. If it doesn't throw, the test fails.
         */
        assertThrows(EateryNotFoundException.class,
                () -> eateryService.findById(eateryId));

        verify(eateryRepo).findById(eateryId);
    }

    // =========================================================================
    // SECTION 2: findEateriesWithinBounds
    //
    // The repo returns List<Object[]>, where each row is:
    //   [eateryId (UUID), name (String), latitude (Double),
    //    longitude (Double), typeLabel (String)]
    //
    // The method maps these Object[] rows to EateryMapDTO records.
    // =========================================================================

    @Test
    void findEateriesWithinBounds_returnsMappedDTOs() {
        /*
         * Build the raw database result that the repository returns.
         * The native SQL query returns Object[] rows — messy but necessary
         * for PostGIS functions that JPQL can't express directly.
         */
        Object[] row = new Object[]{
                eateryId,
                "Test Hawker",
                1.3,    // latitude (ST_Y of location)
                103.8,  // longitude (ST_X of location)
                "Hawker Stall"
        };
        when(eateryRepo.findWithinBoundingBox(1.2, 1.4, 103.7, 103.9))
                .thenReturn(List.<Object[]>of(row));

        List<EateryMapDTO> results = eateryService.findEateriesWithinBounds(1.2, 1.4, 103.7, 103.9);

        assertEquals(1, results.size());
        EateryMapDTO dto = results.getFirst();
        assertEquals(eateryId, dto.getEateryId());
        assertEquals("Test Hawker", dto.getName());
        assertEquals(1.3, dto.getLatitude(), 1e-9);
        assertEquals(103.8, dto.getLongitude(), 1e-9);
        assertEquals("Hawker Stall", dto.getTypeLabel());

        verify(eateryRepo).findWithinBoundingBox(1.2, 1.4, 103.7, 103.9);
    }

    @Test
    void findEateriesWithinBounds_whenEmpty_returnsEmptyList() {
        when(eateryRepo.findWithinBoundingBox(anyDouble(), anyDouble(), anyDouble(), anyDouble()))
                .thenReturn(List.of());

        List<EateryMapDTO> results = eateryService.findEateriesWithinBounds(10, 20, 50, 60);

        assertTrue(results.isEmpty());
        verify(eateryRepo).findWithinBoundingBox(10, 20, 50, 60);
    }

    // =========================================================================
    // SECTION 3: getEateryDetailed
    //
    // Complex mapping: takes an eatery ID, fetches the entity, iterates over
    // all food entries, computes confidence for each, picks the best per food
    // type, generates presigned URLs, and assembles a nested DTO.
    // =========================================================================

    @Test
    void getEateryDetailed_whenEateryHasEntries_returnsDetailedDTO() {
        /*
         * Build two food entries with different foods.
         * The method should return the best entry per food (highest confidence).
         */
        Food food1 = Food.builder().label("Chicken Rice").photoObjKey("chicken-key").build();
        food1.setId(UUID.randomUUID());

        Food food2 = Food.builder().label("Laksa").photoObjKey("laksa-key").build();
        food2.setId(UUID.randomUUID());

        FoodEntry entry1 = FoodEntry.builder()
                .food(food1)
                .sgCents(400)
                .upvoteCount(10)
                .downvoteCount(2)
                .submitterId(UUID.randomUUID())
                .build();
        entry1.setId(UUID.randomUUID());
        entry1.setCreatedAt(Instant.now());

        FoodEntry entry2 = FoodEntry.builder()
                .food(food2)
                .sgCents(550)
                .upvoteCount(8)
                .downvoteCount(1)
                .submitterId(UUID.randomUUID())
                .build();
        entry2.setId(UUID.randomUUID());
        entry2.setCreatedAt(Instant.now());

        testEatery.setFoodEntries(List.of(entry1, entry2));

        when(eateryRepo.findById(eateryId)).thenReturn(Optional.of(testEatery));
        when(confidenceAlgorithm.computeFinalConfidence(entry1)).thenReturn(75.0);
        when(confidenceAlgorithm.computeFinalConfidence(entry2)).thenReturn(85.0);
        /*
         * The method calls minioStorageService.getPresignedUrl for EACH entry's
         * food photo AND for the eatery's own photo. That's 3 calls in this case:
         * entry1.food, entry2.food, and testEatery.
         */
        when(minioStorageService.getPresignedUrl(anyString(), any(Duration.class)))
                .thenReturn("https://presigned.url/photo");

        EateryDetailedDTO result = eateryService.getEateryDetailed(eateryId);

        assertNotNull(result);
        assertEquals(eateryId, result.eateryId());
        assertEquals("Test Hawker", result.name());
        assertEquals("Hawker Stall", result.typeLabel());
        assertEquals(2, result.foodPreviews().size());

        /*
         * Verify the correct presigned URL calls were made.
         * getPresignedUrl is called 3 times (2 entries + 1 eatery).
         */
        verify(minioStorageService, times(3))
                .getPresignedUrl(anyString(), any(Duration.class));
    }

    @Test
    void getEateryDetailed_whenEateryHasNoEntries_returnsEmptyPreviews() {
        testEatery.setFoodEntries(List.of());

        when(eateryRepo.findById(eateryId)).thenReturn(Optional.of(testEatery));
        when(minioStorageService.getPresignedUrl(testEatery.getPhotoObjKey(), Duration.ofMinutes(30)))
                .thenReturn("https://presigned.url/photo");

        EateryDetailedDTO result = eateryService.getEateryDetailed(eateryId);

        assertNotNull(result);
        assertTrue(result.foodPreviews().isEmpty());
    }

    // =========================================================================
    // SECTION 4: searchForEateries
    // =========================================================================

    @Test
    void searchForEateries_returnsMatchingResults() {
        Object[] row = new Object[]{eateryId, "Test Hawker", "1 Test Street"};
        when(eateryRepo.findBySearchCaseInsensitive("test"))
                .thenReturn(List.<Object[]>of(row));

        List<EateryPreviewDTO> results = eateryService.searchForEateries("test");

        assertEquals(1, results.size());
        assertEquals("Test Hawker", results.getFirst().name());
        verify(eateryRepo).findBySearchCaseInsensitive("test");
    }

    @Test
    void searchForEateries_whenNoMatch_returnsEmptyList() {
        when(eateryRepo.findBySearchCaseInsensitive("nonexistent")).thenReturn(List.of());

        List<EateryPreviewDTO> results = eateryService.searchForEateries("nonexistent");

        assertTrue(results.isEmpty());
        verify(eateryRepo).findBySearchCaseInsensitive("nonexistent");
    }
}
