spring:
  application:
    name: eureka-discovery-server
  config:
    import: "optional:file:.env[.properties]"
server:
  port: ${APP_PORT}
eureka:
  instance:
    hostname: ${HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${HOSTNAME}:${APP_PORT}/eureka/
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF