apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: api-gateway:1.0 # The image you loaded earlier
          imagePullPolicy: Never # CRITICAL: Don't look online for this image
          ports: # Listening on
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: api-gateway-secrets # Refers to kustomization yaml
