apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort # So it can be reached from outside the Minikube network...
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080 # Listening on
      targetPort: 8080 # Forwards to
      nodePort: 30080 # ...This is the port exposed to your host machine [Works in conjunction with type: NodePort]
