apiVersion: v1
kind: Service
metadata:
  name: user-service # This will be the DNS hostname for other services to call
spec:
  selector:
    app: user-service # Pattern to find the pods
  ports:
    - name: http
      port: 8080 # Listening on (and, implicitly, forwards to)
    - name: grpc
      port: 9090 # Listening on (and, implicitly, forwards to)
