spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
  config:
    import: "optional:file:.env[.properties]"
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 60s
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
server:
  port: ${APP_PORT}
app:
  routing:
    user-service: ${USER_SERVICE_URI}
    food-service: ${FOOD_SERVICE_URI}
    ai-service: ${AI_SERVICE_URI}
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
