spring:
  application:
    name: api-gateway
  config:
    import: "optional:file:.env.local[.properties]"
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5000
server:
  port: ${APP_PORT}
